### PR TITLE
Fixed install/remove of kapacitor on non-systemd Debian/Ubuntu systems

### PR DESCRIPTION
**Pull request by martinseener**
Also added distribution-specific install/remove logic with code copied from telegraf/influxdb scripts. For more rationale, see: https://github.com/influxdata/telegraf/pull/2360

###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by martinseener** [comment]
Just tell me if it's fine to add it to the CHANGELOG.md to the next version or you could do it yourself. thanks ;)

**Comment by martinseener** [comment]
Don't know why it actually fails :(

**Comment by martinseener** [comment]
Is there a reason, this has not been merged yet?

**Comment by nathanielc** [comment]
@martinseener Thanks for the good work here. I have incorporated these changes into #1663.

**Pull request closed without merging**
