### PR TITLE
Fixes missing To property on email.

### LINKED ISSUE #602: Kapacitor fails to define task with email "to" property
I am unable to define a task that sends out email alert to a specific email address when CRITICAL is breached.  

Here are details of my host:

**Operating System:** Ubuntu 14.04 (64-bit)
**Kapacitor version:**  Kapacitor 0.13.0 (git: master ce28f6dced073e473b44f592517fa6c4d05b5e65)
**Install source:**   Pre-built package 

I was following online documentation at https://docs.influxdata.com/kapacitor/v0.13/nodes/alert_node/

My tick script looks this:

```
vagrant@default-ubuntu-1404:~$ cat cpu_alert.tick
stream
    |from()
        .measurement('cpu')
    |alert()
        // Compare values to running mean and standard deviation
        .crit(lambda: "usage_idle" <  99)
        .log('/tmp/alerts.log')
        .email().to("oiwunze@mydomain.com")
```

However, when I try to run `kapacitor define` on the script it fails

```
vagrant@default-ubuntu-1404:~$ kapacitor define cpu_alert -type stream -tick cpu_alert.tick -dbrp telegraf.default
invalid TICKscript: line 9 char 18: no method or property "to" on *pipeline.EmailHandler
```

I only able to define the task successfully if I remove `to("oiwunze@mydomain.com")` 

Assuming I configure smtp in kapacitor.conf to send all alerts to the email address above I still get no alerts.  I have tested locally on the server that I can send email using the mail command.

### PR DESCRIPTION
**Pull request by nathanielc**
Fixes #602 Somehow it got removed at somepoint :(
We need to add tests for the SMTP service, but I'll need a good SMTP mock server. For now lets just fix this issue.

- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by wunzeco** [comment]
@nathanielc 

Thanks for fixing #602 quickly. Any chance you could make Kapacitor v0.13.1 release available in your Apt and Yum repositories please?  I'd like to install kapacitor from the package repos and verify that I'm no longer experiencing the issue I reported in #602.

Cheers

**Comment by nathanielc** [comment]
@wunzeco Kapacitor 1.0.0-beta1 was released today with the fix.

**Comment by wunzeco** [comment]
@nathanielc That's awesome. But I suspect v1.0.0-beta1 is yet to be published to your Yum and Debian package repositories. Take a look a look at https://repos.influxdata.com/ubuntu/dists/trusty/stable/binary-amd64/Packages

**Comment by nathanielc** [comment]
@wunzeco You can use the unstable path https://repos.influxdata.com/ubuntu/dists/trusty/unstable/binary-amd64/Packages

**Comment by wunzeco** [comment]
@nathanielc Thanks

**Pull request merged**
