### PR TITLE
moving docs #624 to kap

### PR DESCRIPTION
**Pull request by beckettsean**
ports https://github.com/influxdata/docs.influxdata.com/pull/624 changes to Kapacitor docs source.

### CODE REVIEW

**Comment by beckettsean** [comment]
@rkuchan @goller @nathanielc

**Comment by nathanielc** [comment]
I think changing `is used to modify the window node` to `is called` or `is set` is still clear and reads a little easier.

**Comment by beckettsean** [comment]
@nathanielc good recommendation. Done. 

Is this the right pattern for updating Kap auto-gen docs?

**Comment by nathanielc** [comment]
@beckettsean Yes, this works great!

**Pull request merged**
