### PR TITLE
Add linear support for QueryNode.fill

### PR DESCRIPTION
**Pull request by SamuelToh**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

###### Required only if applicable
_You can erase any checkboxes below this note if they are not applicable to your Pull Request._
- [x] [TICKscript Spec](https://github.com/influxdata/kapacitor/blob/master/tick/TICKscript.md) updated

### CODE REVIEW

**Comment by SamuelToh** [comment]
@nathanielc Git noob here. So earlier on, at [here](https://github.com/influxdata/kapacitor/pull/1432) you spoke about squashing all the commits and rebasing my fork. 

Tried doing that, and since before my submission I actually did a bad move by syncing my fork repository by _git merge_ instead of _git rebase_, so I thought I will just revert the merge first before rebasing again.

Reverted the merge and I did a rebase, somehow managed to get to a state where the commit log looks as thou I have just forked from the main repository. Good but it seems like Github had automatically closed my pull request, so I made a new one here... Hopefully this won't be an issue for you to merge.

**Comment by nathanielc** [comment]
@SamuelToh No worries. Not sure why github closed the other PR but this one will work. Can you update the changelog to reflect the new PR number? Then a simple rebase +squash should work since you have a nice commit history now.

Also in the future it is helpful to create a new branch on your fork of the repo so that you can sync with upstream and then rebase off the updated local master branch.

Example git workflow:

1. Fork repo and add upstream remote: `git remote add upstream `http://....`
2. Create new local branch `git checkout -b <name of branch> master`
3. Make changes
4. Sync with upstream `git fetch upstream master:master`
5. Rebase off updated master `git rebase -i master`
6. Push change and submit PR: `git push`

**Comment by SamuelToh** [comment]
@nathanielc I have squashed the commits. We should be all good now. Let me know if there is still problems.
Thanks for the git tips. I'll do that on my next pull request.

**Comment by SamuelToh** [comment]
@nathanielc Is this an intermittent issue? Because I had updated was CHANGELOG.md.

Test_Combination_Count, "failed with error: === RUN   Test_Combination_Count".

**Comment by nathanielc** [comment]
@SamuelToh I reran the build and its green now. We have a few of those intermittent failures we are trying to track down.

**Pull request merged**
