### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by timhallinflux**
Reordered bugfix/features in descending order now that 1.2.0 is released.

###### Required for all non-trivial PRs
- [ ] Rebased/mergable
- [ ] Tests pass
- [x] CHANGELOG.md updated
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

###### Required only if applicable
_You can erase any checkboxes below this note if they are not applicable to your Pull Request._
- [ ] [TICKscript Spec](https://github.com/influxdata/kapacitor/blob/master/tick/TICKscript.md) updated

### CODE REVIEW

**Comment by nathanielc** [comment]
@timhallinflux Looks like the features are still not ordered correctly.

**Comment by timhallinflux** [comment]
updated for the three digit issues.

**Comment by nathanielc** [comment]
@timhallinflux Looks good. Should I go back and do this for all previous releases to be consistent?

**Comment by timhallinflux** [comment]
I can I go back and do this quickly.  Look for a future PR.

**Pull request merged**
