### PR TITLE
[services:OpsGenie] changed Description field

### PR DESCRIPTION
**Pull request by andreasnuesslein**
`.opsGenie()` will now use `|alert()`s `.details()` field for the description.
This breaks the old behavior of using `event.Data.Result` (which could not be changed) and draws level with the other alerting services.

Ticket addressing this: https://github.com/influxdata/kapacitor/issues/1130

###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by nathanielc** [comment]
@nutztherookie This is great! Thanks.

I think it can be quite simple to make this not a breaking change. Adding a simple configuration option to the opsgenie config to enable this behavior would work. This way its opt-in to the new behavior but once its turned on, its on for all ops-genie alerts.

See https://github.com/influxdata/kapacitor/pull/1686 for an example of a very similar change to the VictorOps integration.

**Comment by nutztherookie** [comment]
@nathanielc  just so you know; the opsGenie recovery did not work (anymore). At least not for me. When I started looking into it, I realized the service is using the old v1 API; opsGenie has v2 now. 
It's set up a wee bit differently (the way the API-URLs are structured) than e.g. PagerDuty I think.

Long story short: I'm restructuring the file a tad, I hope that's fine with you as long as the result is pretty again? :)

**Comment by nathanielc** [comment]
@nutztherookie Sounds good, maybe we can just set a version option in the config which will toggle all these updates.

**Comment by nutztherookie** [comment]
@nathanielc quick question: there is no way to save a return value in an alert is there?
OpsGenie returns a unique ID for the alert by which it could be addressed later on. It's also fine to use the alias but the other way would be clearer.

**Comment by nutztherookie** [comment]
@nathanielc 
- I didn't include the returned ID for now and I'm using the `alias` for everything. 
- I did also not do the config-version-thingy. The only reason for that would be to keep the .json-output-compliance, which I would rather integrate if really necessary. I don't think anybody would benefit from just keeping the old (deprecated) API.
- The new API changed the authentication-method: Instead of the api-key being in the payload, it's now a header `Authorization: GenieKey eb243592-faa2-4ba2-a551q-1afdf565c889` (https://docs.opsgenie.com/v1.0/docs/alert-api)  .. I updated most tests accordingly but the one remaining I can't figure out and was hoping you could help? :) 

thanks

**Comment by nutztherookie** [comment]
@nathanielc 
I found the last bug, :)
please let me know if you want a backwards compatibility flag for the old `.details()` behavior.

happy new year!

**Comment by fdhex** [comment]
@nutztherookie thanks for your work! Looking forward to have this merged.

**Comment by yonido** [comment]
Can we expedite this PR for the next release? this is very important : ) +1 !

**Comment by nathanielc** [comment]
@andreasnuesslein @yonido We have added an opsgenie2 implementation in this PR #1823 which should address most of these issues and uses the new v2 API. Closing this PR to keep the old handler backwards compatible.

**Comment by nathanielc** [comment]
Further explanation of why this PR was closed since it was not quite clear with my initial comment. 

This PR represents a set of new features added to the OpsGenie alert integration for Kapacitor. These change are backwards incompatible with the current integration. In order to accept these changes we need to apply them to a new handler. The work in #1823 set the ground work for these new changes, primarily it created a new OpsGenie handler called opsgenie2 and it uses the v2 API.

The next steps are to apply the changes this PR made to the original opsgenie code to the new opsgenie2 code instead.

**Comment by abadyan-vonage** [comment]
Guys, is there a plan to merge these sweet improvements to opsgenie2?
@andreasnuesslein @nathanielc

**Comment by andreasnuesslein** [comment]
@abadyan-vonage sorry not from my side

**Comment by fdhex** [comment]
@nathanielc I was pretty happy to see my code suggestions from back then were going to be merged as we're still using them in prod! Unfortunate that we are stuck with the previous behavior...

**Pull request closed without merging**
