### PR TITLE
Fix batch queries missing all fields after the first nil field

### LINKED ISSUE #1294: Kapacitor record query does not return same points as line protocol query
Initial problem description is [here](https://groups.google.com/forum/#!topic/influxdb/url8JfKqt2s), but that didn't elicit any response.

I've a couple of days on this issue now and have more to report. This issue is a big deal for me, because I'm using kapacitor to run a calculation algorithm on live data. I routinely make improvements to the algorithm and wish to run it on historical data before committing to the live stream. The bug described here makes that infuriatingly complex.

As described in the [original post](https://groups.google.com/d/msg/influxdb/url8JfKqt2s/Senm8KiRAAAJ), kapacitor's record query does not return the same points as influx's queries. This makes constructing the queries an endless game of trial and error. Here's what I've discovered:

- `SELECT *` in influx returns all tags and fields, including time. In kapacitor it only returns the first field by alphabetical order!
- `SELECT field1, tag1` does not return the tag in kapacitor.
- `SELECT field1 ... GROUP BY *` does return the tags, but ordered by tag values, not by time. This makes replaying useless.
- `SELECT field1, field2` does not return field2 unless the point also has a field1 set.

Putting all this together, I've come up with a horrendous workaround for replaying historical data.

First consider this example measurement where a and b are fields and t is a tag:

```
name: m

time a b t
---- - - -
1    1   x
2      2 y
3    3   x 
4      4  y
```

I could find no way to replay this data to a kapacitor stream script. Instead, I found this:

```
influx
> SELECT a,t INTO "m_flat" FROM m WHERE t='x'
> SELECT b AS a, t  INTO "m_flat" FROM m WHERE t='y'
```

That creates a new measurement where t is now a field, like so:

```
name: m_flat

time a t
---- - -
1    1 x
2    2 y
3    3 x 
4    4 y
```

Then, in my kapacitor script I call a UDF which restores the tags:

```
  if point.name == "m_flat": #then unflatten
    point.tags['t'] = point.fieldsString['t']
    point.fieldsDouble['b'] = point.fieldsDouble['a']
```

And finally, I can record and replay:

```
RID=$(kapacitor record query -query $'SELECT a,t FROM "db"."autogen"."m_flat" WHERE time > \'2017-02-27T16:30:00Z\' AND time < \'2017-03-01T16:30:00Z\' ' -type stream)
kapacitor replay -task calc_history -recording $RID -rec-time
```

I have to repeat for every two day time periods because the API kapacitor uses is limited to 10000 rows. Surely this is not intended functionality?

### PR DESCRIPTION
**Pull request by nathanielc**
Fixes #1294 , @hraftery do you have the ability to build and test out this PR to confirm it fixes your issue?

- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by hraftery** [comment]
@nathanielc I do now! I've set up a dev environment and run my tests both with and without the PR. Initially looked good, but ran into problems. Certainly appears to fix the first issue in #1294 :

- `SELECT *` in influx returns all tags and fields, including time. In kapacitor it only returns the first field by alphabetical order!

I then went back and tried it against the [original report](https://groups.google.com/forum/#!msg/influxdb/url8JfKqt2s/Senm8KiRAAAJ). Also looking good.

Observe:

```
~/gocode/bin/influx -execute "drop database d"
~/gocode/bin/influx -execute "create database d"
~/gocode/bin/influx -execute 'INSERT m a=1 1' -database d
~/gocode/bin/influx -execute 'INSERT m b=2 2' -database d
~/gocode/bin/influx -execute 'INSERT m,t1=3 a=3,b=3 3' -database d
~/gocode/bin/influx -execute 'INSERT m,t2=4 a=4,b=4 4' -database d
~/gocode/bin/influx -execute 'INSERT m,t1=5 a=5,b=5 5' -database d
~/gocode/bin/influx -execute 'INSERT m,t1=6 b=6 6' -database d
~/gocode/bin/influx -execute 'INSERT m,t2=7 b=7 7' -database d
~/gocode/bin/influx -execute 'INSERT m,t1=8 b=8 8' -database d
~/gocode/bin/influx -execute 'INSERT m,t1=9 b=9 9' -database d
~/gocode/bin/influx -execute 'INSERT m b=10 10' -database d
~/gocode/bin/influx -execute 'INSERT m a=11 11' -database d
~/gocode/bin/influx -execute 'SELECT * FROM m' -database d
```

Which gives:

```
name: m
time a  b  t1 t2
---- -  -  -- --
1    1        
2       2     
3    3  3  3  
4    4  4     4
5    5  5  5  
6       6  6  
7       7     7
8       8  8  
9       9  9  
10      10    
11   11   
```

Now:

```
~/gocode/bin/kapacitor define record_issue -type stream -tick record_issue.tick  -dbrp d.autogen
rid=$(~/gocode/bin/kapacitor record query -query $'SELECT * FROM "d"."autogen"."m"' -type stream)
~/gocode/bin/kapacitor replay -task record_issue -recording $rid -rec-time
```

Then `/var/log/kapacitor/kapacitor.log` shows:

```
[task_master:d5c5f8e5-b4fd-4cfd-832c-1a3ef849ecf0] 2017/04/15 08:29:43 I! opened
[task_master:d5c5f8e5-b4fd-4cfd-832c-1a3ef849ecf0] 2017/04/15 08:29:43 I! Started task: record_issue
[record_issue:log2] 2017/04/15 08:29:43 I! RECORD_ISSUE {"Name":"m","Database":"d","RetentionPolicy":"autogen","Group":"","Dimensions":{"ByName":false,"TagNames":null},"Tags":{},"Fields":{"a":1},"Time":"1970-01-01T00:00:00.000000001Z"}
[record_issue:log2] 2017/04/15 08:29:43 I! RECORD_ISSUE {"Name":"m","Database":"d","RetentionPolicy":"autogen","Group":"","Dimensions":{"ByName":false,"TagNames":null},"Tags":{},"Fields":{"b":2},"Time":"1970-01-01T00:00:00.000000002Z"}
[record_issue:log2] 2017/04/15 08:29:43 I! RECORD_ISSUE {"Name":"m","Database":"d","RetentionPolicy":"autogen","Group":"","Dimensions":{"ByName":false,"TagNames":null},"Tags":{},"Fields":{"a":3,"b":3,"t1":"3"},"Time":"1970-01-01T00:00:00.000000003Z"}
[record_issue:log2] 2017/04/15 08:29:44 I! RECORD_ISSUE {"Name":"m","Database":"d","RetentionPolicy":"autogen","Group":"","Dimensions":{"ByName":false,"TagNames":null},"Tags":{},"Fields":{"a":4,"b":4,"t2":"4"},"Time":"1970-01-01T00:00:00.000000004Z"}
[record_issue:log2] 2017/04/15 08:29:44 I! RECORD_ISSUE {"Name":"m","Database":"d","RetentionPolicy":"autogen","Group":"","Dimensions":{"ByName":false,"TagNames":null},"Tags":{},"Fields":{"a":5,"b":5,"t1":"5"},"Time":"1970-01-01T00:00:00.000000005Z"}
[record_issue:log2] 2017/04/15 08:29:44 I! RECORD_ISSUE {"Name":"m","Database":"d","RetentionPolicy":"autogen","Group":"","Dimensions":{"ByName":false,"TagNames":null},"Tags":{},"Fields":{"b":6,"t1":"6"},"Time":"1970-01-01T00:00:00.000000006Z"}
[record_issue:log2] 2017/04/15 08:29:44 I! RECORD_ISSUE {"Name":"m","Database":"d","RetentionPolicy":"autogen","Group":"","Dimensions":{"ByName":false,"TagNames":null},"Tags":{},"Fields":{"b":7,"t2":"7"},"Time":"1970-01-01T00:00:00.000000007Z"}
[record_issue:log2] 2017/04/15 08:29:44 I! RECORD_ISSUE {"Name":"m","Database":"d","RetentionPolicy":"autogen","Group":"","Dimensions":{"ByName":false,"TagNames":null},"Tags":{},"Fields":{"b":8,"t1":"8"},"Time":"1970-01-01T00:00:00.000000008Z"}
[record_issue:log2] 2017/04/15 08:29:44 I! RECORD_ISSUE {"Name":"m","Database":"d","RetentionPolicy":"autogen","Group":"","Dimensions":{"ByName":false,"TagNames":null},"Tags":{},"Fields":{"b":9,"t1":"9"},"Time":"1970-01-01T00:00:00.000000009Z"}
[record_issue:log2] 2017/04/15 08:29:44 I! RECORD_ISSUE {"Name":"m","Database":"d","RetentionPolicy":"autogen","Group":"","Dimensions":{"ByName":false,"TagNames":null},"Tags":{},"Fields":{"b":10},"Time":"1970-01-01T00:00:00.00000001Z"}
[record_issue:log2] 2017/04/15 08:29:44 I! RECORD_ISSUE {"Name":"m","Database":"d","RetentionPolicy":"autogen","Group":"","Dimensions":{"ByName":false,"TagNames":null},"Tags":{},"Fields":{"a":11},"Time":"1970-01-01T00:00:00.000000011Z"}
[task_master:d5c5f8e5-b4fd-4cfd-832c-1a3ef849ecf0] 2017/04/15 08:29:44 I! Stopped task: record_issue
[task_master:d5c5f8e5-b4fd-4cfd-832c-1a3ef849ecf0] 2017/04/15 08:29:44 I! closed
```

So all data accounted for and all in order, but all tags have become fields. So next I tried to test the other main sub-issue:


- `SELECT field1 ... GROUP BY *` does return the tags, but ordered by tag values, not by time. This makes replaying useless.

by recording with GROUP BY:

```
~/gocode/bin/kapacitor define record_issue -type stream -tick record_issue.tick  -dbrp d.autogen
rid=$(~/gocode/bin/kapacitor record query -query $'SELECT * FROM "d"."autogen"."m" GROUP BY *' -type stream)
```

And the call never returns. `kapacitord` locks up and needs a kill -9 and `influxd` starts spitting out `[I] 2017-04-14T22:38:51Z Post http://localhost:9092/write?consistency=&db=telegraf&precision=ns&rp=autogen: net/http: request canceled (Client.Timeout exceeded while awaiting headers) service=subscriber`.

Alas, it looks like a small step forward and a big step backward. Maybe there was a reason for that `break` statement!

Further info: it's the `~/gocode/bin/influx -execute 'INSERT m,t1=5 a=5,b=5 5' -database d` point that causes the lock up. With the first 4 points, no problems. As soon as I try to put that 5th point in to test the out of order issue, it locks up. In fact, `GROUP BY t2` is enough.

**Comment by nathanielc** [comment]
@hraftery Thanks for the detailed writeup, I'll take a look at the second set of issues.

**Comment by nathanielc** [comment]
@hraftery  I have fixed the second issue. Basically the first issue was masking another hidden bug that caused an infinite loop in the ordering logic for recordings. At this point your test (using GROUP BY *) should work, and the recording should contain all the data in order by time. Can you give it a try when you get a chance?

**Comment by hraftery** [comment]
Looks great. Quite a process to update and test, but results look good.

**Comment by nathanielc** [comment]
@hraftery Thanks for going through the effort. I'll get this merged and cut a new beta release of 1.3.0

**Pull request merged**
