### PR TITLE
Buffer pooling alert post request body buffer

### PR DESCRIPTION
**Pull request by yosiat**
Added buffer pooling for post handler in alert.

I tried to add benchmark for this, by using `httptest.NewServer` and got: `accept: too many open files`, I tried to increase the maximum file descriptors to 4096 and didn't helped.

### CODE REVIEW

**Comment by nathanielc** [comment]
@yosiat Looks good thanks.

**Comment by yosiat** [comment]
@nathanielc can you think of a way we can benchmark the post handler of alert?

**Comment by nathanielc** [comment]
Using `httptest.NewServer` should work, `accept: too many open files` should only occur if the requests were being made massively parallel or they were not being closed after use. Could you share the code you wrote initially? 

Also I merged because it was a simple enough change that I didn't think it merited its own benchmark (it does have a test). But if you want to add the benchmark I am happy to help.

**Comment by yosiat** [comment]
@nathanielc The code created httptest.NewServer and doing nothing in the handler function, and I passed the url of the httptest to the post handler, nothing special here.

I think I got the error (might be because of #572) or because we have 1000 tasks, which means 1000 requests..

**Comment by nathanielc** [comment]
@yosiat  I think you are right. Worth trying again once its merged.

**Pull request merged**
