### PR TITLE
Minor change to build.py

### PR DESCRIPTION
**Pull request by rossmcdonald**
This change brings back parity to InfluxDB build script.

### CODE REVIEW

**Comment by nathanielc** [comment]
+1 on green, Thanks a ton for keeping these in sync. Have you tried the kapacitor -> influxdb port yet? do you need any help?

**Comment by rossmcdonald** [comment]
@nathanielc I merged the bulk of the changes yesterday with https://github.com/influxdata/influxdb/pull/5596, but this should be the last one needed to get everything in sync. I think I have everything under control for now, but I'll let you know if things get too complicated.

**Comment by nathanielc** [comment]
Great, second commit looks good too. Thanks

**Comment by rossmcdonald** [comment]
Hmm, failure here was:

```
There are un-committed changes in your local branch, --no-stash was given, cannot continue
```

Which was originally getting skipped, but is now handled. I don't know why there would be un-committed changes in the directory, though.

**Comment by nathanielc** [comment]
Go generate must have changed some files, meaning the committed ones are out of date with the source of the generated files. Which is a valid reason to stop the build. I'll see if I can figure out what is up.

**Comment by rossmcdonald** [comment]
Same failure. I'm guessing this is from the changes made by `go generate`? Should `--no-stash` be given if generate is called?

**Comment by rossmcdonald** [comment]
Ah, that makes sense.

**Comment by rossmcdonald** [comment]
@nathanielc I added debug output to the build command. It's move verbose and shows the underlying commands being run, which should hopefully help a little with debugging. Let me know if you have any concerns, or want to leave it as-is.

**Comment by rossmcdonald** [comment]
Files that changed are:

```
 M vendor/github.com/influxdb/influxdb/cluster/internal/data.pb.go
 M vendor/github.com/influxdb/influxdb/services/copier/internal/internal.pb.go
 M vendor/github.com/influxdb/influxdb/services/meta/internal/meta.pb.go
 M vendor/github.com/influxdb/influxdb/tsdb/internal/meta.pb.go
```

**Comment by nathanielc** [comment]
Hmm, I'll fix that....

On Fri, Feb 26, 2016 at 11:31 AM, Ross McDonald <notifications@github.com>
wrote:

> Files that changed are:
>
>  M vendor/github.com/influxdb/influxdb/cluster/internal/data.pb.go
>  M vendor/github.com/influxdb/influxdb/services/copier/internal/internal.pb.go
>  M vendor/github.com/influxdb/influxdb/services/meta/internal/meta.pb.go
>  M vendor/github.com/influxdb/influxdb/tsdb/internal/meta.pb.go
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/influxdata/kapacitor/pull/262#issuecomment-189414058>.
>



-- 
*Nathaniel Cook*
Kapacitor Lead
▼▴

*InfluxData.com <http://influxdata.com/>*

Twitter <http://www.twitter.com/nathanielvcook>

**Comment by nathanielc** [comment]
@rossmcdonald I fixed the go generate issue, now something else is broken. Looks like the test deps didn't get installed.

**Comment by rossmcdonald** [comment]
@nathanielc Test dependency issue resolved! I also squashed a few commits. Assuming the latest check passes, I think this is ready to go.

**Pull request merged**
