### PR TITLE
issue #1043 wrong file mode on kapacitor logrotate configuration

### PR DESCRIPTION
**Pull request by winem**
###### Required for all non-trivial PRs
- [X] Rebased/mergable
- [ ] Tests pass
- [X] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

###### Required only if applicable
_You can erase any checkboxes below this note if they are not applicable to your Pull Request._
- [ ] [TICKscript Spec](https://github.com/influxdata/kapacitor/blob/master/tick/TICKscript.md) updated

### CODE REVIEW

**Comment by nathanielc** [comment]
@winem Thanks! this looks good. Can you sign the CLA and rebase again?

**Comment by winem** [comment]
@nathanielc sure, will do it this evening.

**Comment by winem** [comment]
@nathanielc Rebased and signed the CLA.

**Comment by nathanielc** [comment]
@rossmcdonald This looks good to me, can you take a quick look?

**Pull request merged**
