### PR TITLE
add feature to detect string edge 

### PR DESCRIPTION
**Pull request by rezamirzaei**
###### Required for all non-trivial PRs
- [ ] Rebased/mergable
- [ ] Tests pass
- [ ] CHANGELOG.md updated
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

###### Required only if applicable
_You can erase any checkboxes below this note if they are not applicable to your Pull Request._
- [ ] [TICKscript Spec](https://github.com/influxdata/kapacitor/blob/master/tick/TICKscript.md) updated

### CODE REVIEW

**Comment by nathanielc** [comment]
@rezamirzaei I don't think this approach is going to work well. Adding string support to the derivative node makes little sense. We could add a an edgeDetect node that supports strings and is well defined for how that works. Adding it to the derivative node will be confusing to users and will not be very discoverable as a feature. I can help provide pointers on how to add an `edgeDetect` node if you want.

Closing.

**Comment by rezamirzaei** [comment]
@nathanielc Thank you for pay attention. i agree with you. i'm glad if you help me in the way you say.
Thank you

**Comment by nathanielc** [comment]
@rezamirzaei Have a look at the StateCount node https://docs.influxdata.com/kapacitor/v1.3/nodes/state_count_node/

You might be able to use the StateCount node directly if your edge is in a binary state. If not then create a copy of the StateCount node and modify it to track the last state and output values when an edge is found.

**Comment by rezamirzaei** [comment]
@nathanielc Thank you for your response.

**Pull request closed without merging**
