### PR TITLE
Support multiple influxdb clusters [WIP]

### LINKED ISSUE #233: Support multiple InfluxDB clusters.
Just need to name them and then flag one as a default.

### PR DESCRIPTION
**Pull request by nathanielc**
Fixes #233 blocked on #155 a bug in the config parser is breaking support for multiple influxdb cluster configs.

### CODE REVIEW

**Comment by panda87** [comment]
@nathanielc that's include multiple servers per cluster?
For example, [server1,server2,server3]

**Comment by nathanielc** [comment]
@panda87  No this is so you can have multiple independent clusters. But the fix for the other is coming soon too...

**Comment by panda87** [comment]
Thanks

**Comment by nathanielc** [comment]
Changed PR, now Fixes #142 and is not blocked on #155

**Pull request merged**
