### PR TITLE
fix derivative preserving fields from wrong point in stream

### PR DESCRIPTION
**Pull request by phemmer**
#1333 changed the derivative node to add the derivative to the current point instead of the previous one. However due to a typo in the code, for stream nodes, it effectively resulted the emitted point containing the values of the previous point, the timestamp of the current point, and the derivative of the current point.

When using batch, the result was as it's supposed to be (values, timestamp, and derivative all from the current point). The batch code had the same typo, it worked because of ordering of the code.

Unfortunately there were no tests that would have caught the behavior, so I added some.

###### Required for all non-trivial PRs
- [X] Rebased/mergable
- [X] Tests pass
- [x] CHANGELOG.md updated
- [X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by nathanielc** [comment]
@phemmer Thanks! I'll take a look at this tomorrow.

**Comment by nathanielc** [comment]
@phemmer We are planning to release a version 1.3.1 with this fix. Can you change the PR to target the `v1.3` branch? Thanks

**Comment by phemmer** [comment]
branch changed.

**Comment by desa** [comment]
LGTM 👍

**Comment by desa** [comment]
@phemmer can you rebase onto `v1.3` and drop the other commits?

**Comment by phemmer** [comment]
Whoops. Didn't notice that after I switched the branch. Done.
Should I also add a note to the CHANGELOG?

**Comment by nathanielc** [comment]
@phemmer 

> Should I also add a note to the CHANGELOG?

Yes please, I added a 1.3.1 section.

**Comment by phemmer** [comment]
done

**Pull request merged**
