### PR TITLE
fix panic if as() is inconsistent with join()

### PR DESCRIPTION
**Pull request by jonseymour**
Previously, if the arguments passed to as() were not consistent with
the number of arms of a join() node, an index out of range panic
would occur at runtime.

Now, we fail during definition of the tick script if the number of
arguments to the as() method is inconsistent or if the as() method was omitted completely.

Signed-off-by: Jon Seymour <jon@wildducktheories.com>

### CODE REVIEW

**Comment by jonseymour** [comment]
This should fix #331

**Comment by jonseymour** [comment]
Having fixed this issue, it isn't clear to me why the join.as() properties method has the behaviour it does.

In particular, it is defined as adding a prefix to the names derived from each parent stream. So, consider this example:

```var metric1 = stream
        |from()
                .database('sampledb')
                .retentionPolicy('default')
                .measurement('sample')
                .groupBy('node')
        |window()
                .align()
                .period(5m)
                .every(5m)
        |shift(-5m)
        |mean('metric1').as('metric1')


var metric2 = stream
        |from()
                .database('sampledb')
                .retentionPolicy('default')
                .measurement('sample')
                .groupBy('node')
        |window()
                .align()
                .period(5m)
                .every(5m)
        |shift(-5m)
        |mean('metric2').as('metric2')

metric1
        |join(metric2)
           .as('m1', 'm2')
        |log()
```

The resulting stream has fields called 'm1.metric1' and 'm2.metric2'. Furthermore, I can't use a common prefix for both arms of the join - so I can't get 'j.metric1' and 'j.metric2'.

While I understand the need to assign unique names to each of the output fields, my expectation would be the names specified to the as() method are the actual names of the outputs and not prefixes as currently implemented.

**Comment by jonseymour** [comment]
Actually, I understand the reason now -for cases where there is a join between two nodes which have multiple fields. I am going to raise another issue about a suggestion about a better way to handle this,

**Comment by jonseymour** [comment]
This PR contains an implementation of #443. I will re-roll this PR if #443 is accepted first.

**Comment by nathanielc** [comment]
@jonseymour I merged #443 this looks good to go after a rebase.

**Comment by nathanielc** [comment]
Closing in favor of #509

**Pull request closed without merging**
