### PR TITLE
apply env to array elements

### LINKED ISSUE #348: applyEnvOverrides fails to override array elements
The following environment override:

```
KAPACITOR_INFLUXDB_URLS_0=http://influx:8086 kapacitord config
```

doesn't have the expected effect.

An attempt is made to ecursively apply overrides to array/slice elements, but the attempt fails because the recursive call returns early because the reflect.Value being operated on by the recursive call is not a struct.

### PR DESCRIPTION
**Pull request by jonseymour**
This fixes #348.

In particular:

```KAPACITOR_INFLUXDB_0_URLS_0=http://localhost:9000 kapacitord config```

should now produce a config which does the expected thing.

### CODE REVIEW

**Comment by nathanielc** [comment]
@jonseymour Thanks for the PR, I know I don't have any tests around config parsing, but could you add a test that demonstrates the new behavior? Don't worry about testing everything else just the changes. We will get to the other tests in time.

**Comment by jonseymour** [comment]
Ok, I'll add tests. I'll have to abstract the call to os.GetEnv() to allow tests to mock this call, as required.

**Comment by jonseymour** [comment]
@nathanielc I've extended a test and done a more complete reorganisation to simplify the structure of the applyEnvOverrides function.

**Comment by jonseymour** [comment]
Actually, I missed an additional simplifcation that is now possible. I'll re-roll.

**Comment by nathanielc** [comment]
@jonseymour Just to make sure, you made that last simplification correct? Also can you add a changelog entry? Otherwise this looks good to go. Thanks!

**Comment by jonseymour** [comment]
Yes, simplifications complete. Changelog now updated.

**Comment by offlinehacker** [comment]
Nice, this should remove sed magic from my Docker image, thanks!

**Pull request merged**
