### PR TITLE
Add links to pagerduty2 alerts

### PR DESCRIPTION
**Pull request by onlynone**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

This feature allows one to do:

```
alert()
  .pagerDuty2()
    .link('http://some.example.com/here', 'here')
    .link('http://other.example.com/there', 'there')
```

To add a list of custom links to pagerduty alerts. They'll be put in the `links` field of the body sent to `https://events.pagerduty.com/v2/enqueue` as per the docs here: https://v2.developer.pagerduty.com/docs/send-an-event-events-api-v2. Both the URL and text fields are treated as templates so one can interpolate fields/tags/etc. The link text is optional and will default to the link url when missing.

### CODE REVIEW

**Comment by onlynone** [comment]
I don't *think* the test failures are related to my code:

```
--- FAIL: TestServer_AlertHandlers (7.93s)
    --- PASS: TestServer_AlertHandlers/alerta-0 (0.24s)
    --- PASS: TestServer_AlertHandlers/exec-1 (0.31s)
    --- PASS: TestServer_AlertHandlers/hipchat-2 (0.40s)
    --- PASS: TestServer_AlertHandlers/kafka-3 (3.28s)
    --- PASS: TestServer_AlertHandlers/log-4 (0.17s)
    --- PASS: TestServer_AlertHandlers/mqtt-5 (0.17s)
    --- PASS: TestServer_AlertHandlers/opsgenie-6 (0.16s)
    --- PASS: TestServer_AlertHandlers/opsgenie2-7 (0.18s)
    --- PASS: TestServer_AlertHandlers/pagerduty-8 (0.17s)
    --- PASS: TestServer_AlertHandlers/pagerduty2-9 (0.20s)
    --- PASS: TestServer_AlertHandlers/post-10 (0.29s)
    --- PASS: TestServer_AlertHandlers/post-11 (0.30s)
    --- PASS: TestServer_AlertHandlers/pushover-12 (0.26s)
    --- PASS: TestServer_AlertHandlers/sensu-13 (0.28s)
    --- PASS: TestServer_AlertHandlers/slack-14 (0.26s)
    --- PASS: TestServer_AlertHandlers/smtp-15 (0.32s)
    --- FAIL: TestServer_AlertHandlers/snmptrap-16 (0.23s)
    	server_test.go:10405: snmptrap: unexpected snmptrap request:
    		exp
    		[{Pdu:{IsNil:false Type:SNMPTrapV2 ErrorStatus:NoError ErrorIndex:0 VarBinds:[{Oid:1.3.6.1.2.1.1.3.0 Value:1000 Type:TimeTicks} {Oid:1.3.6.1.6.3.1.1.4.1.0 Value:1.1.2 Type:Oid} {Oid:1.1.2.1 Value:message Type:OctetString} {Oid:1.1.2.2 Value:CRITICAL Type:OctetString}]} Error:<nil>}]
    		got
    		[]
    --- PASS: TestServer_AlertHandlers/talk-17 (0.20s)
    --- PASS: TestServer_AlertHandlers/tcp-18 (0.17s)
    --- PASS: TestServer_AlertHandlers/telegram-19 (0.17s)
    --- PASS: TestServer_AlertHandlers/victorops-20 (0.17s)
```

**Comment by onlynone** [comment]
@stevebang @russorat @nathanielc @timhallinflux I'd love some feedback on this feature.

**Comment by onlynone** [comment]
It looks like all tests passed but the test just exited with a 1 exit code? I grepped through the output and I see 830 tests run, 829 tests passed, and 1 test skipped.

**Comment by onlynone** [comment]
@stevebang @russorat @nathanielc @timhallinflux Can someone take a look at this? Also, is there a way to trigger another test build run?

**Comment by onlynone** [comment]
@stevebang @russorat @nathanielc @timhallinflux I've merged master and made a tweak to the changelog which forced a new build which succeeded this time. Anything else I can do?

**Comment by rbetts** [comment]
Can you clarify how this fits with: https://github.com/influxdata/kapacitor/issues/2081.  Thanks for the contribution. Help me sort out what (if at all) overlaps and we will review this for K. 1.5.2.

**Pull request merged**
