### PR TITLE
Alert handler for Microsoft Teams

### PR DESCRIPTION
**Pull request by mmindenhall**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

###### Required only if applicable
_You can erase any checkboxes below this note if they are not applicable to your Pull Request._
N/A

This adds support for sending alerts via Microsoft Teams (similar to Slack or HipChat).  I followed the [alert handlers guide](https://github.com/influxdata/kapacitor/blob/master/alert/HANDLERS.md) where possible, and when I ran into problems, I looked at the source code for other alerts (e.g., HipChat).  The tests implemented follow the same pattern of tests performed by the HipChat handler.

All tests are passing for me locally (except some unrelated UDF tests which fail due to python issues on my Mac).

### CODE REVIEW

**Comment by mmindenhall** [comment]
Is there anyone who can take a look at this?  @nathanielc?  I'll be happy to update the docs once this is approved and merged.

**Comment by te4336** [comment]
Has this been merged as a change? I know that we use this heavily internally and this feature would be a huge plus.

**Comment by StefanSa** [comment]
@nathanielc
as we switch from slack to ms teams, this would be a big help for us as well.

**Comment by StefanSa** [comment]
@mmindenhall
Thanks for teams webhook.
Can you change the color of the Webhook cards, similar to slack, depending on the alert status (crtitical, warning etc.)?

For example, with cards fields
`themeColor": "EA4300"
`

**Comment by dominiclapointe** [comment]
Is this planned to be merged soon?

**Comment by Gelob** [comment]
Wonder as well if this will be merged soon?

**Comment by mmindenhall** [comment]
@StefanSa, unfortunately there is no way to change the theme or text color within a card.  I agree that this is a significant shortcoming compared to Slack.

**Comment by StefanSa** [comment]
@mmindenhall  think that is not 100% correct.
An example as sh script, zabbix to teams:
https://github.com/spasticate/zabbix-MSTeams-alertscript/blob/master/teams.sh

or alerta to teams:
https://github.com/alerta/alerta-contrib/blob/master/plugins/msteams/alerta_msteams.py

**Comment by mmindenhall** [comment]
Ah, yes, you are right @StefanSa. I never tried the `themeColor` setting for this plugin, but had included it in a similar Java notifier library I wrote for some of our other projects.

According to the [message card reference](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference), the setting is intended for branding rather than communicating status:

themeColor | String | Specifies a custom brand color for the card. The color will be displayed in a non-obtrusive manner.<br><br>Do use themeColor to brand cards to your color.<br>Don't use themeColor to indicate status.
-- | -- | :--

It would be easy to add to the card...but all it does is change the color of a line across the top of the card ([screenshot](https://imgur.com/9hb1tfM)).

**Comment by StefanSa** [comment]
@mmindenhall 
For me it works as expected with this example.

Playground on MS
https://messagecardplayground.azurewebsites.net

Alert
```{
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    "themeColor": "EA4300",
    "summary": "Larry Bryant created a new task",
    "sections": [
        {
            "activityTitle": "Service ftp1-server /cpu is  CRITICAL CPU is at 99.70",
              "facts": [
                {
                    "name": "Assigned to",
                    "value": "Unassigned"
                },
                {
                    "name": "Due date",
                    "value": "Mon May 01 2017 17:07:18 GMT-0700 (Pacific Daylight Time)"
                },
                {
                    "name": "Status",
                    "value": "Not started"
                }
            ],
            "markdown": true
        }
    ]
  }
```
OK
```{
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    "themeColor": "00AA5A",
    "summary": "Larry Bryant created a new task",
    "sections": [
        {
            "activityTitle": "Service ftp1-server /cpu is  OK CPU is at 1",
              "facts": [
                {
                    "name": "Assigned to",
                    "value": "Unassigned"
                },
                {
                    "name": "Due date",
                    "value": "Mon May 01 2017 17:07:18 GMT-0700 (Pacific Daylight Time)"
                },
                {
                    "name": "Status",
                    "value": "Not started"
                }
            ],
            "markdown": true
        }
    ]
  }
```

**Comment by mmindenhall** [comment]
@StefanSa, I think the best way to implement support for `themeColor` would be to add additional elements to the Teams config struct to enable/disable using the `themeColor`, and to define colors (with defaults) for each alert level.  For example, this might be the default configuration: 

```toml
[teams]
theme-color-enabled = true  # enabled by default
ok-color = "008000"         # green
info-color = "008080"       # teal
warning-color = "FFFF00"    # yellow
critical-color = "FF0000"   # red
max-level-color = "800000"  # maroon
```

When the theme color is enabled, the Teams handler will configure the card with the color matching the alert level.

HOWEVER, it's been more than 10 months since I submitted this PR, and for some reason the team has ignored it completely.  I don't plan to add to this PR unless/until it either gets merged, or the team lets me know what needs to be done for it to be merged.

**Comment by StefanSa** [comment]
@mmindenhall yes, unfortunately it has become quiet around kapacitor.
I have a bug ticket open since mid-December, with no response. Apparently all the energy and power goes into the development of influxdb v2.

@nathanielc @rbetts 
Is there a chance to accelerate this whole, otherwise the community probably loses the desire to contribute something to the project here.

**Comment by syates21** [comment]
@StefanSa It doesn't seem like it's *that* quiet, as many other pull requests have been accepted.  Hard to think of a good reason why nice work like this that has no conflicts wouldn't be accepted.  I can't think of a few really lame reasons (mostly having to do with bias towards certain vendors).

**Comment by StefanSa** [comment]
So that there is no further speculation, it would be helpful if explained here why this good PR
not accepted / was.
This is not necessarily motivating, for the _so-much-touted_ community.

**Comment by danlange** [comment]
Please merge this.  Microsoft Teams support is an important feature to those of us who use Microsoft Teams.

**Comment by jgoeglein** [comment]
Bump and +1 . Is there any word on what needs to happen to move this one along?

Also, as an aside as to why this PR is important, [Microsoft Teams is now bigger than Slack](https://www.cnbc.com/2019/07/11/microsoft-teams-passes-slack-in-daily-users-rajesh-jha-explains-why.html)

**Comment by pwalleni** [comment]
Please accept this.

**Comment by stephen-burrows** [comment]
I'm investigating whether my company can use TICK. This feature is vital for us (thanks, mmindenhall for creating it!). Can we have an indication as to whether it's going to be merged?

**Comment by Clausewitz45** [comment]
More than a year, and this is still open. Every check passed, except the merge button. This is an important feature, please just merge.

**Comment by UpperM** [comment]
I did a little script in the meantime. If it helps... Https://github.com/UpperM/kapacitor-msteams

**Comment by chazragg** [comment]
any news on this ?

**Comment by GlossyPanther** [comment]
pls merge :(

**Comment by easybe** [comment]
Hi.

I am actually also very interested in this. Unfortunately, the company I work for loves M$ and their products, so, Teams it is.

It would indeed be nice to get some feedback from @nathanielc or anyone else form @Influxdata.

I could also help hands-on if that is what it takes.

Cheers,
Ezra.

**Comment by hexinal** [comment]
Any news @nathanielc ?

**Comment by kevinpz** [comment]
Hi everyone! 

We would really like to use Kapacitor at my current company as well, and since all our communications use Microsoft Teams, this is a real blocker for us.
Is there any thing we can do to help this PR to be merged @nathanielc ?

Thanks a lot!

**Comment by plaurin84** [comment]
Hi,
I totally need this feature! :+1:

**Comment by mattnotmitt** [comment]
Hey @docmerlin I saw you've been going through other PRs, any plans to review this one?

**Comment by docmerlin** [comment]
@mattnotmitt I do!  I have to get a Microsoft Teams account first to test it though.

**Comment by mertbakir** [comment]
Hi, I see that this is merged already. Is this feature available or waiting for next release? May I ask the eta for next release?

**Comment by southbay82** [comment]
Great to see this was merged. Like what @mertbakir mentioned, is there a preferred means to monitor for upcoming releases and features/fixes contained within?

**Comment by mattnotmitt** [comment]
@southbay82 click the Watch button on the repository and choose "releases only". You'll get an email/github notification when a release gets pushed on the repo. [CHANGELOG.md](https://github.com/influxdata/kapacitor/blob/master/CHANGELOG.md) should contain any updates when the release is created.

**Comment by sinistram** [comment]
When will you planning to release this feature?

**Comment by Tower450** [comment]
The documentation is there but it do not seems to be released right?
Documentation URL: https://docs.influxdata.com/kapacitor/v1.5/event_handlers/microsoftteams/#set-up-teams

I tried it and i ended up with this error while declaring a topic-handler

```
failed to create handler: unsupported action kind "teams"
```

Any update about this?

**Comment by mertbakir** [comment]
OK this works now with Kapacitor 1.8.5 but it sends:
{{.Level}} {{.ID}} as title
.message as body.

**It should be:**
.message as title
.details as body.

Can we fix this? Should I open a new issue?
Also, chronograf needs a small update to add Teams as a handler.

**Comment by senses0** [comment]
I'm running Kapacitor 1.5.6-1 and Chronograf 1.8.5-1, and I've enabled Teams Event Handler as described here https://docs.influxdata.com/kapacitor/v1.5/event_handlers/microsoftteams/#set-up-teams

Kapacitor service restarts fine (no apparent errors in log messages) after configuration changes, however I'm not seeing "Teams" in Chronograf under "Alert Handlers", which I am guessing it should. Am I missing anything?

**Comment by msrpub** [comment]
> @StefanSa, unfortunately there is no way to change the theme or text color within a card. I agree that this is a significant shortcoming compared to Slack.

Which is the limitation? If we look for instance to Grafana Alerts via webhooks they have a kind of separator red or green according to the status. Could it be implemented in similar way?

**Comment by msrpub** [comment]
> OK this works now with Kapacitor 1.8.5 but it sends:
> {{.Level}} {{.ID}} as title
> .message as body.
> 
> **It should be:**
> .message as title
> .details as body.
> 
> Can we fix this? Should I open a new issue?
> Also, chronograf needs a small update to add Teams as a handler.

Did you addressed this as an issue?

**Comment by mertbakir** [comment]
> > OK this works now with Kapacitor 1.8.5 but it sends:
> > {{.Level}} {{.ID}} as title
> > .message as body.
> > 
> > **It should be:**
> > .message as title
> > .details as body.
> > 
> > Can we fix this? Should I open a new issue?
> > Also, chronograf needs a small update to add Teams as a handler.
> 
> Did you addressed this as an issue?
> 

No, I didn't.

**Pull request merged**
