### PR TITLE
Stateful expression tests

### PR DESCRIPTION
**Pull request by yosiat**
Covering more cases:
* EvalNum: "-4"
* EvalBool: "!true"
* Sanity function calling - count()
* EvalNum for number node

### CODE REVIEW

**Comment by nathanielc** [comment]
@yosiat This looks great. Thanks. One quick thing in a few places `unexpected` is misspelled as `unexpectedd`.

**Comment by yosiat** [comment]
@nathanielc  this kinda ironic after i submit a PR to fix misspells ;)
Will fix that :)

**Comment by nathanielc** [comment]
@yosiat  I only spotted it because my mind was in spell mode after reviewing your PR ;)

**Comment by yosiat** [comment]
@nathanielc changed

**Comment by yosiat** [comment]
@nathanielc ok.. this weird.. we are failing because of:
```
=== RUN   TestServer_UDFBatchAgents
[srv] 2016/04/14 16:25:12 I! Kapacitor hostname: localhost
[srv] 2016/04/14 16:25:12 I! ClusterID: 844e7e6d-c940-40df-a439-6793348443b2 ServerID: e139601e-700d-4580-a3d1-a837520e8f5c
[task_master] 2016/04/14 16:25:12 I! opened
[srv] 2016/04/14 16:25:12 D! opening service: *udf.Service
[udf] 2016/04/14 16:25:12 I!P 2016/04/14 16:25:12 Starting agent
[udf] 2016/04/14 16:25:12 D! loaded UDF info "outliers"
[srv] 2016/04/14 16:25:12 D! opened service: *udf.Service
[srv] 2016/04/14 16:25:12 D! opening service: *deadman.Service
[srv] 2016/04/14 16:25:12 D! opened service: *deadman.Service
[srv] 2016/04/14 16:25:12 D! opening service: *influxdb.Service
[influxdb] 2016/04/14 16:25:12 I! linking subscriptions
[srv] 2016/04/14 16:25:12 D! opened service: *influxdb.Service
[srv] 2016/04/14 16:25:12 D! opening service: *task_store.Service
[srv] 2016/04/14 16:25:12 D! opened service: *task_store.Service
[srv] 2016/04/14 16:25:12 D! opening service: *replay.Service
[srv] 2016/04/14 16:25:12 D! opened service: *replay.Service
[srv] 2016/04/14 16:25:12 D! opening service: *stats.Service
[stats] 2016/04/14 16:25:12 I! opened service
[srv] 2016/04/14 16:25:12 D! opened service: *stats.Service
[srv] 2016/04/14 16:25:12 D! opening service: *httpd.Service
[httpd] 2016/04/14 16:25:12 I! Starting HTTP service
[httpd] 2016/04/14 16:25:12 I! Authentication enabled: false
[httpd] 2016/04/14 16:25:12 I! Listening on HTTP: 127.0.0.1:58129
[srv] 2016/04/14 16:25:12 D! opened service: *httpd.Service
[httpd] 2016/04/14 16:25:12 I! 127.0.0.1 - - [14/Apr/2016:16:25:12 +0000] POST /task?dbrps=%5B%7B%22db%22%3A%22mydb%22%2C%22rp%22%3A%22myrp%22%7D%5D&name=testUDFTask&type=batch HTTP/1.1 204 0 - KapacitorClient 763ecc26-025d-11e6-8056-000000000000 5.373716ms
[task_master] 2016/04/14 16:25:12 D! Starting task: testUDFTask
[task_master] 2016/04/14 16:25:12 I! Started task: testUDFTask
[task_master] 2016/04/14 16:25:12 D! digraph testUDFTask {
batch1 -> outliers2;
outliers2 -> count3;
count3 -> http_out4;
}
[httpd] 2016/04/14 16:25:12 I! 127.0.0.1 - - [14/Apr/2016:16:25:12 +0000] POST /enable?name=testUDFTask HTTP/1.1 204 0 - KapacitorClient 763fc14b-025d-11e6-8057-000000000000 20.346253ms
[testUDFTask:batch1] 2016/04/14 16:25:12 D! starting next batch query: SELECT value FROM mydb.myrp.cpu WHERE time >= '2016-04-14T16:25:12.072791558Z' AND time < '2016-04-14T16:25:12.077791558Z' GROUP BY count
[testUDFTask:batch1] 2016/04/14 16:25:12 D! starting next batch query: SELECT value FROM mydb.myrp.cpu WHERE time >= '2016-04-14T16:25:12.077903326Z' AND time < '2016-04-14T16:25:12.082903326Z' GROUP BY count
[httpd] 2016/04/14 16:25:12 I! 127.0.0.1 - - [14/Apr/2016:16:25:12 +0000] GET /task/testUDFTask/count HTTP/1.1 200 46 - Go-http-client/1.1 764362b8-025d-11e6-8058-000000000000 15.273244ms
[testUDFTask:batch1] 2016/04/14 16:25:12 D! starting next batch query: SELECT value FROM mydb.myrp.cpu WHERE time >= '2016-04-14T16:25:12.083976737Z' AND time < '2016-04-14T16:25:12.088976737Z' GROUP BY count
[testUDFTask:batch1] 2016/04/14 16:25:12 D! starting next batch query: SELECT value FROM mydb.myrp.cpu WHERE time >= '2016-04-14T16:25:12.088901528Z' AND time < '2016-04-14T16:25:12.093901528Z' GROUP BY count
[testUDFTask:batch1] 2016/04/14 16:25:12 D! starting next batch query: SELECT value FROM mydb.myrp.cpu WHERE time >= '2016-04-14T16:25:12.090118103Z' AND time < '2016-04-14T16:25:12.095118103Z' GROUP BY count
[testUDFTask:batch1] 2016/04/14 16:25:12 D! starting next batch query: SELECT value FROM mydb.myrp.cpu WHERE time >= '2016-04-14T16:25:12.099506941Z' AND time < '2016-04-14T16:25:12.104506941Z' GROUP BY count
[testUDFTask:outliers2] 2016/04/14 16:25:12 I!P 2016/04/14 16:25:12 Starting agent
[testUDFTask:batch1] 2016/04/14 16:25:12 D! starting next batch query: SELECT value FROM mydb.myrp.cpu WHERE time >= '2016-04-14T16:25:12.105509682Z' AND time < '2016-04-14T16:25:12.110509682Z' GROUP BY count
[testUDFTask:batch1] 2016/04/14 16:25:12 D! starting next batch query: SELECT value FROM mydb.myrp.cpu WHERE time >= '2016-04-14T16:25:12.117228685Z' AND time < '2016-04-14T16:25:12.122228685Z' GROUP BY count
[testUDFTask:batch1] 2016/04/14 16:25:12 D! starting next batch query: SELECT value FROM mydb.myrp.cpu WHERE time >= '2016-04-14T16:25:12.126848397Z' AND time < '2016-04-14T16:25:12.131848397Z' GROUP BY count
[testUDFTask:batch1] 2016/04/14 16:25:12 D! starting next batch query: SELECT value FROM mydb.myrp.cpu WHERE time >= '2016-04-14T16:25:12.137910999Z' AND time < '2016-04-14T16:25:12.142910999Z' GROUP BY count
[testUDFTask:batch1] 2016/04/14 16:25:12 D! starting next batch query: SELECT value FROM mydb.myrp.cpu WHERE time >= '2016-04-14T16:25:12.1511081Z' AND time < '2016-04-14T16:25:12.1561081Z' GROUP BY count
[httpd] 2016/04/14 16:25:12 I! 127.0.0.1 - - [14/Apr/2016:16:25:12 +0000] GET /task/testUDFTask/count HTTP/1.1 200 137 - Go-http-client/1.1 76534961-025d-11e6-8059-000000000000 2.979073ms
[edge:testUDFTask|batch->batch0] 2016/04/14 16:25:12 D! closing c: 11 e: 10
[edge:testUDFTask|batch1->outliers2] 2016/04/14 16:25:12 D! closing c: 11 e: 11
[edge:testUDFTask|outliers2->count3] 2016/04/14 16:25:12 D! closing c: 11 e: 10
==================
WARNING: DATA RACE
Write by goroutine 131:
  runtime.closechan()
      /usr/local/go/src/runtime/chan.go:292 +0x0
  github.com/influxdata/kapacitor.(*Edge).Close()
      /root/go/src/github.com/influxdata/kapacitor/edge.go:121 +0x29a
  github.com/influxdata/kapacitor.(*node).closeChildEdges()
      /root/go/src/github.com/influxdata/kapacitor/node.go:190 +0xa5
  github.com/influxdata/kapacitor.(*node).start.func1.1()
      /root/go/src/github.com/influxdata/kapacitor/node.go:112 +0x66
  github.com/influxdata/kapacitor.(*node).start.func1()
      /root/go/src/github.com/influxdata/kapacitor/node.go:129 +0xb4

Previous read by goroutine 84:
  runtime.chansend()
      /usr/local/go/src/runtime/chan.go:115 +0x0
  github.com/influxdata/kapacitor.(*Edge).CollectBatch()
      /root/go/src/github.com/influxdata/kapacitor/edge.go:185 +0x222
  github.com/influxdata/kapacitor.(*UDFNode).runUDF.func2()
      /root/go/src/github.com/influxdata/kapacitor/udf.go:107 +0x478

Goroutine 131 (running) created at:
  github.com/influxdata/kapacitor.(*node).start()
      /root/go/src/github.com/influxdata/kapacitor/node.go:129 +0x60
  github.com/influxdata/kapacitor.(*UDFNode).start()
      <autogenerated>:1335 +0x69
  github.com/influxdata/kapacitor.(*ExecutingTask).start.func2()
      /root/go/src/github.com/influxdata/kapacitor/task.go:212 +0x155
  github.com/influxdata/kapacitor.(*ExecutingTask).walk()
      /root/go/src/github.com/influxdata/kapacitor/task.go:136 +0xea
  github.com/influxdata/kapacitor.(*ExecutingTask).start()
      /root/go/src/github.com/influxdata/kapacitor/task.go:215 +0x225
  github.com/influxdata/kapacitor.(*TaskMaster).StartTask()
      /root/go/src/github.com/influxdata/kapacitor/task_master.go:335 +0x87b
  github.com/influxdata/kapacitor/services/task_store.(*Service).StartTask()
      /root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:686 +0xd6
  github.com/influxdata/kapacitor/services/task_store.(*Service).enableRawTask()
      /root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:651 +0x17c
  github.com/influxdata/kapacitor/services/task_store.(*Service).Enable()
      /root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:672 +0x15f
  github.com/influxdata/kapacitor/services/task_store.(*Service).handleEnable()
      /root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:461 +0xc2
  github.com/influxdata/kapacitor/services/task_store.(*Service).(github.com/influxdata/kapacitor/services/task_store.handleEnable)-fm()
      /root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:125 +0x4b
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1618 +0x47
  github.com/influxdata/kapacitor/services/httpd.jsonContent.func1()
      /root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:489 +0xb7
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1618 +0x47
  github.com/influxdata/kapacitor/services/httpd.gzipFilter.func1()
      /root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:482 +0x2da
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1618 +0x47
  github.com/influxdata/kapacitor/services/httpd.versionHeader.func1()
      /root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:498 +0xea
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1618 +0x47
  github.com/influxdata/kapacitor/services/httpd.cors.func1()
      /root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:531 +0x395
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1618 +0x47
  github.com/influxdata/kapacitor/services/httpd.requestID.func1()
      /root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:541 +0x1c7
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1618 +0x47
  github.com/influxdata/kapacitor/services/httpd.logging.func1()
      /root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:549 +0x145
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1618 +0x47
  github.com/influxdata/kapacitor/services/httpd.recovery.func1()
      /root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:559 +0x169
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:1618 +0x47
  github.com/influxdata/kapacitor/services/httpd.(*ServeMux).ServeHTTP()
      /root/go/src/github.com/influxdata/kapacitor/services/httpd/mux.go:163 +0x212
  github.com/influxdata/kapacitor/services/httpd.(*Handler).ServeHTTP()
      /root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:230 +0x511
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2081 +0x206
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1472 +0x1565

Goroutine 84 (finished) created at:
  github.com/influxdata/kapacitor.(*UDFNode).runUDF()
      /root/go/src/github.com/influxdata/kapacitor/udf.go:116 +0x2db
  github.com/influxdata/kapacitor.(*UDFNode).(github.com/influxdata/kapacitor.runUDF)-fm()
      /root/go/src/github.com/influxdata/kapacitor/udf.go:49 +0x59
  github.com/influxdata/kapacitor.(*node).start.func1()
      /root/go/src/github.com/influxdata/kapacitor/node.go:128 +0x9f
==================
FAIL	github.com/influxdata/kapacitor/cmd/kapacitord/run	19.231s
```

**Comment by nathanielc** [comment]
@yosiat That is a known race that I haven't been able to track down yet.  #274 Should be unrelated to your changes.
I'll bounce a rebuild.

**Pull request merged**
