### PR TITLE
upgrade github.com/gorhill/cronexpr lib

### PR DESCRIPTION
**Pull request by wuguanyu**
###### Required for all non-trivial PRs
- [ ] Rebased/mergable
- [ ] Tests pass
- [ ] CHANGELOG.md updated
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

###### Required only if applicable
_You can erase any checkboxes below this note if they are not applicable to your Pull Request._
- [ ] [TICKscript Spec](https://github.com/influxdata/kapacitor/blob/master/tick/TICKscript.md) updated

### CODE REVIEW

**Comment by wuguanyu** [comment]
upgrade github.com/gorhill/cronexpr version

**Comment by wuguanyu** [comment]
fix bug https://github.com/influxdata/kapacitor/issues/2350

**Comment by wuguanyu** [comment]
this issue lead kapacitor can not start up

**Comment by docmerlin** [comment]
Hey @wuguanyu thanks for this PR, but for us to accept this change you would need to update the Gopkg.toml and Gopkg.lock.  I can do this for you, or you can if you want?

**Comment by wuguanyu** [comment]
> Hey @wuguanyu thanks for this PR, but for us to accept this change you would need to update the Gopkg.toml and Gopkg.lock. I can do this for you, or you can if you want?

Sorry Can you help me change update the Gopkg.toml and Gopkg.lock

**Comment by docmerlin** [comment]
Will do!

**Pull request merged**
