### PR TITLE
add http response close

### PR DESCRIPTION
**Pull request by upccup**

### CODE REVIEW

**Comment by upccup** [comment]
if the http response body is not close the tcp socket will be 'ESTABLISHED' in a long time  liake this
```
tcp        0      0 127.0.0.1:36186         127.0.0.1:8080          ESTABLISHED 24744/post
tcp        0      0 127.0.0.1:36184         127.0.0.1:8080          ESTABLISHED 24744/post
tcp6       0      0 :::8080                 :::*                    LISTEN      24740/gin
tcp6       0      0 127.0.0.1:8080          127.0.0.1:36186         ESTABLISHED 24740/gin
tcp6       0      0 127.0.0.1:8080          127.0.0.1:36183         ESTABLISHED 24740/gin
tcp6       0      0 127.0.0.1:8080          127.0.0.1:36188         ESTABLISHED 24740/gin
tcp6       0      0 127.0.0.1:8080          127.0.0.1:36180         ESTABLISHED 24740/gin
tcp6       0      0 127.0.0.1:8080          127.0.0.1:36182         ESTABLISHED 24740/gin
tcp6       0      0 127.0.0.1:8080          127.0.0.1:36181         ESTABLISHED 24740/gin
tcp6       0      0 127.0.0.1:8080          127.0.0.1:36185         ESTABLISHED 24740/gin
tcp6       0      0 127.0.0.1:8080          127.0.0.1:36187         ESTABLISHED 24740/gin
tcp6       0      0 127.0.0.1:8080          127.0.0.1:36184         ESTABLISHED 24740/gin
......
```

**Comment by yosiat** [comment]
Maybe this is the reason I got ``accept: too many open files`` while trying to benchmark alert's post in #547

**Comment by nathanielc** [comment]
@upccup Thanks for the PR! Look good. Can you rebase to fix an issue with the build? that should fix your failed checks.

Also you will need to sign the CLA before I can merge.

**Comment by upccup** [comment]
@nathanielc i have rebased so i can not understand why the test failed  because i  do not change the file in github.com/influxdata/kapacitor/cmd/kapacitor but the test error is ?   	github.com/influxdata/kapacitor/cmd/kapacitor	[no test files]

**Comment by nathanielc** [comment]
@upccup Try rebasing against latest master again, there was an upstream issue with a build dep, should be fixed now.

**Pull request closed without merging**
