### PR TITLE
reduce allocs and map indexes for CollectPoint

### PR DESCRIPTION
**Pull request by nathanielc**
Adds benchmarks from @yosiat.

Two changes, instead of statsMap.Add using direct reference to *expvar.Int to avoid map look up.

Changed args to incCollected/incEmitted to not require heap allocation.

Adds benchmark for edge.CollectPoint directly. 
Improvement is good:

```
benchmark                    old ns/op     new ns/op     delta
Benchmark_CollectPoint-8     1031          707           -31.43%

benchmark                    old allocs     new allocs     delta
Benchmark_CollectPoint-8     2              0              -100.00%

benchmark                    old bytes     new bytes     delta
Benchmark_CollectPoint-8     256           0             -100.00%
```

Improvement on full write test is good too.
```
benchmark                                            old ns/op       new ns/op      delta
Benchmark_Write_MeasurementNameNotMatches_1000-4     6273967891      4240956941     -32.40%
Benchmark_Write_MeasurementNameMatches_1000-4        6708792279      4503474984     -32.87%
Benchmark_Write_MeasurementNameNotMatches_100-4      7768092706      4973414305     -35.98%
Benchmark_Write_MeasurementNameMatches_100-4         8383660564      5157680889     -38.48%
Benchmark_Write_MeasurementNameNotMatches_10-4       9831826369      5263307437     -46.47%
Benchmark_Write_MeasurementNameMatches_10-4          10232057586     5258015149     -48.61%

benchmark                                            old allocs     new allocs     delta
Benchmark_Write_MeasurementNameNotMatches_1000-4     15462870       57439          -99.63%
Benchmark_Write_MeasurementNameMatches_1000-4        19313940       3901498        -79.80%
Benchmark_Write_MeasurementNameNotMatches_100-4      23090665       4292295        -81.41%
Benchmark_Write_MeasurementNameMatches_100-4         23742484       4800160        -79.78%
Benchmark_Write_MeasurementNameNotMatches_10-4       24095167       4775145        -80.18%
Benchmark_Write_MeasurementNameMatches_10-4          24147784       4890630        -79.75%

benchmark                                            old bytes      new bytes     delta
Benchmark_Write_MeasurementNameNotMatches_1000-4     1975214888     4262320       -99.78%
Benchmark_Write_MeasurementNameMatches_1000-4        2405864264     434731368     -81.93%
Benchmark_Write_MeasurementNameNotMatches_100-4      2882851768     478502496     -83.40%
Benchmark_Write_MeasurementNameMatches_100-4         2957967752     535381800     -81.90%
Benchmark_Write_MeasurementNameNotMatches_10-4       3002221608     532581984     -82.26%
Benchmark_Write_MeasurementNameMatches_10-4          3008055144     545516640     -81.86%
```

CollectPoint is still spending lots of time counting stats, I am playing around with channels based implementation vs atmoic.Add

### CODE REVIEW

**Comment by nathanielc** [comment]
Using a channel based implementation instead of atomic.Add was not faster.

**Comment by yosiat** [comment]
@nathanielc I think there is a bug in the Benchmark, I am not cleaning after each benchmark the TaskMaster, so we are actually not testing against 100 tasks or 10 tasks.

I am fixing this and will upload new version to yosiat/kapacitor/perf

**Comment by nathanielc** [comment]
@yosiat Ok thanks, either way the CollectPoint benchmark is -30% on its own which seems to translating well to the broader test.

**Comment by yosiat** [comment]
Fixed this:
```
Benchmark_Write_MeasurementNameNotMatches_1000-4	       1	11760042929 ns/op	1975218280 B/op	15468357 allocs/op
Benchmark_Write_MeasurementNameMatches_1000-4   	       1	11509590974 ns/op	2406124968 B/op	19315430 allocs/op
Benchmark_Write_MeasurementNameNotMatches_100-4 	    5000	    205519 ns/op	   54418 B/op	     448 allocs/op
Benchmark_Write_MeasurementNameMatches_100-4    	    5000	    205267 ns/op	   65278 B/op	     545 allocs/op
Benchmark_Write_MeasurementNameNotMatches_10-4  	   50000	     24441 ns/op	    4359 B/op	      53 allocs/op
Benchmark_Write_MeasurementNameMatches_10-4     	   50000	     26836 ns/op	    4468 B/op	      54 allocs/op
ok  	command-line-arguments	84.642s
```

https://github.com/yosiat/kapacitor/commit/22d4616d10d8b90ecfaf059da624e4fc63a4535d

**Comment by yosiat** [comment]
@nathanielc I think a possible performance improvement is to do some api breaking,
and changed "StreamCollect" to accept an array of points.

Therefore, you can increment once for multiple points.

**Comment by nathanielc** [comment]
Here are the correct results, basically the same...
```
benchmark                                            old ns/op      new ns/op      delta
Benchmark_Write_MeasurementNameNotMatches_1000-4     7307662678     4678726431     -35.98%
Benchmark_Write_MeasurementNameMatches_1000-4        6724460416     4460785463     -33.66%
Benchmark_Write_MeasurementNameNotMatches_100-4      23275          15479          -33.50%
Benchmark_Write_MeasurementNameMatches_100-4         23620          15570          -34.08%
Benchmark_Write_MeasurementNameNotMatches_10-4       15458          14639          -5.30%
Benchmark_Write_MeasurementNameMatches_10-4          15396          14486          -5.91%

benchmark                                            old allocs     new allocs     delta
Benchmark_Write_MeasurementNameNotMatches_1000-4     15466521       57447          -99.63%
Benchmark_Write_MeasurementNameMatches_1000-4        19309921       3904833        -79.78%
Benchmark_Write_MeasurementNameNotMatches_100-4      88             48             -45.45%
Benchmark_Write_MeasurementNameMatches_100-4         97             53             -45.36%
Benchmark_Write_MeasurementNameNotMatches_10-4       50             48             -4.00%
Benchmark_Write_MeasurementNameMatches_10-4          51             49             -3.92%

benchmark                                            old bytes      new bytes     delta
Benchmark_Write_MeasurementNameNotMatches_1000-4     1975554248     4264496       -99.78%
Benchmark_Write_MeasurementNameMatches_1000-4        2406015896     435170392     -81.91%
Benchmark_Write_MeasurementNameNotMatches_100-4      8872           3841          -56.71%
Benchmark_Write_MeasurementNameMatches_100-4         9958           4384          -55.98%
Benchmark_Write_MeasurementNameNotMatches_10-4       4104           3843          -6.36%
Benchmark_Write_MeasurementNameMatches_10-4          4157           3896          -6.28%
```

**Comment by nathanielc** [comment]
@yosiat Breaking the API is not a possibility, at least not right now. 

The change you are proposing already exists as CollectBatch. A batch is an array of points with some consolidated metadata.  CollectPoint exists because it was needed in addition to CollectBatch. 

That being said, it doesn't mean we can't group updates and only perform `.Add` every so often. I am playing with something like that now.

**Comment by nathanielc** [comment]
Another significant improvement if groupBy is not being used:
```
benchmark                                            old ns/op      new ns/op      delta
Benchmark_Write_MeasurementNameNotMatches_1000-4     5159738246     3880726492     -24.79%
Benchmark_Write_MeasurementNameMatches_1000-4        4020222956     3481916661     -13.39%
Benchmark_Write_MeasurementNameNotMatches_100-4      15369          15314          -0.36%
Benchmark_Write_MeasurementNameMatches_100-4         15643          15226          -2.67%
Benchmark_Write_MeasurementNameNotMatches_10-4       14435          13266          -8.10%
Benchmark_Write_MeasurementNameMatches_10-4          14664          13217          -9.87%

benchmark                                            old allocs     new allocs     delta
Benchmark_Write_MeasurementNameNotMatches_1000-4     57444          57440          -0.01%
Benchmark_Write_MeasurementNameMatches_1000-4        3905954        57426          -98.53%
Benchmark_Write_MeasurementNameNotMatches_100-4      48             48             +0.00%
Benchmark_Write_MeasurementNameMatches_100-4         53             48             -9.43%
Benchmark_Write_MeasurementNameNotMatches_10-4       48             48             +0.00%
Benchmark_Write_MeasurementNameMatches_10-4          49             48             -2.04%

benchmark                                            old bytes     new bytes     delta
Benchmark_Write_MeasurementNameNotMatches_1000-4     4262656       4262384       -0.01%
Benchmark_Write_MeasurementNameMatches_1000-4        435289880     4261568       -99.02%
Benchmark_Write_MeasurementNameNotMatches_100-4      3841          3842          +0.03%
Benchmark_Write_MeasurementNameMatches_100-4         4385          3842          -12.38%
Benchmark_Write_MeasurementNameNotMatches_10-4       3842          3841          -0.03%
Benchmark_Write_MeasurementNameMatches_10-4          3897          3841          -1.44%
```

**Comment by yosiat** [comment]
@nathanielc why you didn't used "buffer.WriteString" method?

**Comment by nathanielc** [comment]
@yosiat I just missed it, it won't make a performance difference. I'll update it soon

**Pull request merged**
