### PR TITLE
Update python agent code to be python 2 and 3 compatible

### PR DESCRIPTION
**Pull request by nathanielc**
Add python3 support to the python UDF agent code.

- [ ] Rebased/mergable
- [ ] Tests pass
- [ ] CHANGELOG.md updated
- [ ] Add python3 based tests to the server_test.go test suite.

### CODE REVIEW

**Comment by rca** [comment]
Trying this now; first thing to get this working was to use `protobuf==3.5.1`

**Comment by rca** [comment]
I ran into a number of encoding issues that are somewhat sorted out with PR #1750.  I am able to receive streaming data into the UDF, but I'm still not able to successfully send data points out of the UDF.

**Comment by lalat-das** [comment]
Applied both the patch i.e. 
1. pointed by Nathanielc  ( it describes the import specific changes)
2. Then applied "rca"(Roberto)'s patch which describes about using .encode() and making stdin & stdout as .buffer type.

I am able to send and recieve point but as long as the point is 80 columns length. 

If the line protocol complaint point goes beyond 80 column, then EOF exception is raised while reading the size of data in read_loop function.
size = decodeUvarint32(self._in)

 This EOF exception pulls the thread out of the infinite loop then the wait() call ends and the agent process no more able to receive any further points.

Notsure may be because the stin is filled with two consecutive EOF may be because of rca patchmake input as sys.stdin.buffer. I am just speculating it.

**Comment by omdv** [comment]
Hello, is this going to be merged?

**Pull request closed without merging**
