### PR TITLE
always force the file inside the tarball owned by root

### PR DESCRIPTION
**Pull request by lfarkas**
similar to https://github.com/influxdata/telegraf/issues/1704

###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [ ] Tests pass
- [ ] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by nathanielc** [comment]
@lfarkas Thanks!, do we also want to do the same thing for the group?

**Comment by lfarkas** [comment]
yes that would be good.

**Comment by nathanielc** [comment]
@lfarkas I'll merge once that is done. Thanks!

**Comment by nathanielc** [comment]
closing in favor of #1660

**Pull request closed without merging**
