### PR TITLE
Bugfix: fix dead lock in task handle

### PR DESCRIPTION
**Pull request by gwtony**
When create or update task script like this:
```
var status = stream
    |from()
        .measurement('access_status')
        .grou pBy('uuid')
    |log()
```
It will cause dead lock due to unhandled 'FunctionNode' case in taskTypeFromProgram. 
I am not sure if there are any other unhandled cases, so i fix it with default case.

### CODE REVIEW

**Comment by gwtony** [comment]
Error in circleci is 
Waiting for parallel builds to finish...
...
Parallel build failed
No more detail for this failed, how can i fix this ?

**Comment by gunnaraasen** [comment]
Downloading the full container logs from the test run, here are the logs from the failed test:

```
=== RUN   TestServer_UDFStreamAgentsSocket
2017/12/22 07:25:11 Server listening on /tmp/kapacitor_server_test462420324/mirror.go.sock
2017/12/22 07:25:11 Starting agent for connection 0
2017/12/22 07:25:11 Agent for connection 0 finished
2017/12/22 07:25:11 Starting agent for connection 1
2017/12/22 07:25:11 Agent for connection 1 finished
2017-12-22 07:25:12,122 INFO:root: Started server
2017-12-22 07:25:12,522 INFO:root: Starting Agent for connection 1
2017-12-22 07:25:12,532 INFO:root: Agent finished connection 1
2017-12-22 07:25:12,783 INFO:root: Starting Agent for connection 2
2017-12-22 07:25:12,879 INFO:root: Agent finished connection 2
2017/12/22 07:25:12 Server stopped
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x250166a]

goroutine 8175 [running]:
github.com/influxdata/kapacitor/vendor/github.com/boltdb/bolt.(*DB).page(...)
	/root/go/src/github.com/influxdata/kapacitor/vendor/github.com/boltdb/bolt/db.go:793
github.com/influxdata/kapacitor/vendor/github.com/boltdb/bolt.(*Tx).page(...)
	/root/go/src/github.com/influxdata/kapacitor/vendor/github.com/boltdb/bolt/tx.go:576
github.com/influxdata/kapacitor/vendor/github.com/boltdb/bolt.(*Bucket).pageNode(0xc42011eb78, 0x3, 0x13a, 0x7fe4387c5c7f)
	/root/go/src/github.com/influxdata/kapacitor/vendor/github.com/boltdb/bolt/bucket.go:697 +0x20a
github.com/influxdata/kapacitor/vendor/github.com/boltdb/bolt.(*Cursor).search(0xc4205c1870, 0xc420073c70, 0xa, 0x10, 0x3)
	/root/go/src/github.com/influxdata/kapacitor/vendor/github.com/boltdb/bolt/cursor.go:254 +0x75
github.com/influxdata/kapacitor/vendor/github.com/boltdb/bolt.(*Cursor).seek(0xc4205c1870, 0xc420073c70, 0xa, 0x10, 0x0, 0x0, 0x0, 0x474b340, 0xc420a2b3b0, 0x439df8, ...)
	/root/go/src/github.com/influxdata/kapacitor/vendor/github.com/boltdb/bolt/cursor.go:159 +0x19a
github.com/influxdata/kapacitor/vendor/github.com/boltdb/bolt.(*Bucket).Bucket(0xc42011eb78, 0xc420073c70, 0xa, 0x10, 0x17)
	/root/go/src/github.com/influxdata/kapacitor/vendor/github.com/boltdb/bolt/bucket.go:112 +0x1eb
github.com/influxdata/kapacitor/vendor/github.com/boltdb/bolt.(*Tx).Bucket(0xc42011eb60, 0xc420073c70, 0xa, 0x10, 0xc4206baae0)
	/root/go/src/github.com/influxdata/kapacitor/vendor/github.com/boltdb/bolt/tx.go:101 +0x5d
github.com/influxdata/kapacitor/services/storage.(*Bolt).exists(0xc4210e0bc0, 0xc42011eb60, 0xc4206baae0, 0x17, 0x0, 0xc42141a9c0, 0x2)
	/root/go/src/github.com/influxdata/kapacitor/services/storage/bolt.go:89 +0x72
github.com/influxdata/kapacitor/services/storage.(*boltTx).Exists(0xc4212d1980, 0xc4206baae0, 0x17, 0xc4206bfff0, 0xb, 0xc4206baae0)
	/root/go/src/github.com/influxdata/kapacitor/services/storage/bolt.go:165 +0x80
github.com/influxdata/kapacitor/services/storage.(*IndexedStore).GetTx(0xc4204864b0, 0x46dcf60, 0xc4212d1980, 0xc4206bfff0, 0xb, 0xc42141aad0, 0x454acd, 0xc420163750, 0xc42141aaf0)
	/root/go/src/github.com/influxdata/kapacitor/services/storage/indexed.go:160 +0xce
github.com/influxdata/kapacitor/services/storage.(*IndexedStore).Get.func1(0x46dcf60, 0xc4212d1980, 0xc4212d1980, 0x0)
	/root/go/src/github.com/influxdata/kapacitor/services/storage/indexed.go:152 +0x8a
github.com/influxdata/kapacitor/services/storage.DoView(0x46cc2a0, 0xc4210e0bc0, 0xc42080ced0, 0x0, 0x0)
	/root/go/src/github.com/influxdata/kapacitor/services/storage/storage.go:80 +0xb4
github.com/influxdata/kapacitor/services/storage.(*Bolt).View(0xc4210e0bc0, 0xc42080ced0, 0x7fe4387c5868, 0x11)
	/root/go/src/github.com/influxdata/kapacitor/services/storage/bolt.go:23 +0x4f
github.com/influxdata/kapacitor/services/storage.(*IndexedStore).Get(0xc4204864b0, 0xc4206bfff0, 0xb, 0x7fe4387c5879, 0x474b301, 0x88, 0x7fe42569cca8)
	/root/go/src/github.com/influxdata/kapacitor/services/storage/indexed.go:151 +0x1ab
github.com/influxdata/kapacitor/services/task_store.(*taskKV).Get(0xc420d3c290, 0xc4206bfff0, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/src/github.com/influxdata/kapacitor/services/task_store/dao.go:212 +0xa5
github.com/influxdata/kapacitor/services/task_store.(*Service).saveLastError(0xc42010c960, 0xc4206bfff0, 0xb, 0xc421841980, 0x2a, 0xc421075200, 0x1)
	/root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:2041 +0xc5
github.com/influxdata/kapacitor/services/task_store.(*Service).startTask.func1(0xc4209403f0, 0xc42010c960, 0xc420128f00, 0xc42147cf40)
	/root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:2026 +0x309
created by github.com/influxdata/kapacitor/services/task_store.(*Service).startTask
	/root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:2015 +0x1d8
FAIL	github.com/influxdata/kapacitor/server	31.797s
```

**Comment by gwtony** [comment]
All tests passed in my environment.
I ran command:
```
go test $(go list ./... | grep -v /vendor/)
```
No failure was reported.
I ran server test directly, it also passed:
```
go test -v ./server
...
PASS
ok  	github.com/influxdata/kapacitor/server	17.467s
```
My environment：
```
centos: 7.1.1503
golang: 1.9
python: 2.7.5
python-protobuf: 3.5.1
```
Is there any possibility that something in circleci environment cause this failure

**Comment by nathanielc** [comment]
@gwtony Thanks for the fix! Closing in favor of #1827 to resolve conflicts

**Pull request closed without merging**
