### PR TITLE
Use more descriptive name for blocked CIDR ranges

### PR DESCRIPTION
**Pull request by pierwill**
Rename blocked CIDR ranges with more accurate descriptor.

###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass

### CODE REVIEW

**Comment by docmerlin** [comment]
@pierwill This has already been released.  We shouldn't break backwards compatibility.

**Review by docmerlin — CHANGES_REQUESTED** [review]
This breaks backwards compatibility on already released software configs.  We shouldn't break backwards compatibility.

**Comment by pierwill** [comment]
> We shouldn't break backwards compatibility.

Agreed! Can we look into Tim's suggestion above? I'd be happy to help implement it with a little guidance from the team. 😇

**Comment by docmerlin** [comment]
@pierwill Is this something you still plan on doing, or should I close the PR?

**Comment by pierwill** [comment]
I'd still like to get around to this at some point. But we can close this PR.

**Pull request closed without merging**
