### PR TITLE
Remove the pidfile after the server has exited

### LINKED ISSUE #1630: Kapacitord should remove pidfile upon exit
Kapacitord does not remove the pidfile upon exit/termination.

See thread and fixes from Influxd tickets. 
Original thread: https://github.com/influxdata/influxdb/issues/8983
Fix:  https://github.com/influxdata/influxdb/pull/8987

### PR DESCRIPTION
**Pull request by jsternberg**
Fixes #1630.

- [x] Rebased/mergable
- [x] Tests pass
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by nathanielc** [comment]
@jsternberg Thanks for fixing this!

**Comment by nathanielc** [comment]
@jsternberg I am getting this test failure:

```
--- FAIL: TestCommand_PIDFile (1.04s)
	command_test.go:62: unexpected timeout
FAIL
```

**Comment by jsternberg** [comment]
I tried making the close timeout longer. Circle is probably just slower than my local computer.

**Comment by jsternberg** [comment]
@nathanielc the test that I added passed the latest build, but something else panicked. Can you take a look?

**Comment by nathanielc** [comment]
@jsternberg Thanks!

**Pull request merged**
