### PR TITLE
Adding tests to increase coverage for stateful expression test

### PR DESCRIPTION
**Pull request by yosiat**
While implementing the "specialised" stateful expression I found test case I didn't cover

* Supplied reference doesn't exists in BinaryNode{RefNode, NumNode}
* BinaryNode{RefNode,NumNode} value is changed
* BinaryNode{RefNode,NumNode} type is changed from float64 to int64
* BinaryNode{BinaryNode{RefNode,NumNode}, BinaryNode{RefNode,NumNode}}

_I am submitting this as separate PR so the specialised stateful expression won't be big PR_

### CODE REVIEW

**Comment by yosiat** [comment]
The tests are failing because:

```
--- FAIL: TestStream_GroupByWhere (0.01s)
	streamer_test.go:3445: digraph TestStream_GroupByWhere {
		srcstream0 -> stream1;
		stream1 -> groupby2;
		stream1 -> where3;
		where3 -> join5;
		groupby2 -> join5;
		join5 -> eval6;
		eval6 -> window7;
		window7 -> mean8;
		mean8 -> http_out9;
		}
	streamer_test.go:3520: unexpected series tags: i: 1 
		exp map[host:serverA cpu:cpu1] 
		got map[cpu:cpu-total host:serverA]
```

Which is weird..

**Comment by nathanielc** [comment]
@yosiat That test has recently become flaky and needs to be fixed... #474

**Comment by yosiat** [comment]
@nathanielc ok, do you want to rebounce the build or something?

**Comment by nathanielc** [comment]
@yosiat  Rebuilding.. is that not something you can do? I am not always sure what others have access to on the project.

**Comment by yosiat** [comment]
@nathanielc where do you see the rebuild button? It would make sense that I won't have access to rebuild

**Comment by nathanielc** [comment]
Top right of the CircleCI interface. 

image

**Comment by yosiat** [comment]
@nathanielc I don't have this option

**Pull request merged**
