### PR TITLE
Enable markdown in slack attachments #251

### PR DESCRIPTION
**Pull request by xuqingfeng**
###### Required for all non-trivial PRs
- [x] Rebased/mergable
- [x] Tests pass
- [ ] CHANGELOG.md updated
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Comment by xuqingfeng** [comment]
@nathanielc Does this pull can be merged ?

**Comment by nathanielc** [comment]
@xuqingfeng Sorry for the really long delay. We have been in freeze mode for the 1.1 release. That is over now and I can take a look at this PR.

My first question is, should this be a user option to enable mark down formatting?

**Comment by xuqingfeng** [comment]
Everyone loves `markdown`, no need to add another option.

**Comment by nathanielc** [comment]
> Everyone loves markdown, no need to add another option.

OK, I agree :)

Can you update the test [here](https://github.com/influxdata/kapacitor/blob/master/integrations/streamer_test.go#L6499) to reflect this change?

**Comment by xuqingfeng** [comment]
@nathanielc done

**Comment by nathanielc** [comment]
@xuqingfeng Everyting looks good to go. Can you rebase of master and add a CHANGELOG entry? Then I can merge on green. Thanks!

**Comment by xuqingfeng** [comment]
@nathanielc sure

Could you check if it's ok?

**Pull request merged**
