### PR TITLE
Fix links to go straight to latest documentation

### PR DESCRIPTION
**Pull request by framiere**

### CODE REVIEW

**Comment by nathanielc** [comment]
@framiere Thanks. We just updated out docs to have  a `latest` path can you change the `v0.11` to `latest` that was we don't have to do this every release. ;) Thanks again.

**Comment by framiere** [comment]
done

**Comment by nathanielc** [comment]
@framiere  Looks good thanks. Can you sign the CLA real quick? https://influxdb.com/community/cla.html

**Comment by framiere** [comment]
done

**Pull request merged**
