### PR TITLE
Includes the .Duration for the Message and Details on alert #1605

### PR DESCRIPTION
**Pull request by thuck**
#1605

### CODE REVIEW

**Comment by thuck** [comment]
@desa Looks the build system had some issue, but there should be no issues with this. Could you run it again in the CircleCI?

**Comment by desa** [comment]
Looks like this is the failing test


```
=== RUN   TestStream_AlertPagerDuty
--- FAIL: TestStream_AlertPagerDuty (0.02s)
	streamer_test.go:10870: digraph TestStream_Alert {
		stream0 -> from1;
		from1 -> window2;
		window2 -> count3;
		count3 -> alert4;
		}
	streamer_test.go:8115: unequal lists ignoring order:
		got
		([]interface {}) (len=2 cap=2) {
		 (pagerdutytest.Request) {
		  URL: (string) (len=1) "/",
		  PostData: (pagerdutytest.PostData) {
		   ServiceKey: (string) (len=11) "service_key",
		   EventType: (string) (len=7) "trigger",
		   Description: (string) (len=40) "CRITICAL alert for kapacitor/cpu/serverA",
		   Client: (string) (len=9) "kapacitor",
		   ClientURL: (string) (len=30) "http://[::]:39856/kapacitor/v1",
		   Details: (string) (len=615) "{&#34;Name&#34;:&#34;cpu&#34;,&#34;TaskName&#34;:&#34;TestStream_Alert&#34;,&#34;Group&#34;:&#34;host=serverA&#34;,&#34;Tags&#34;:{&#34;host&#34;:&#34;serverA&#34;},&#34;ServerInfo&#34;:{&#34;Hostname&#34;:&#34;localhost&#34;,&#34;ClusterID&#34;:&#34;3d0c012f-06cc-4415-a388-9221d12bf14c&#34;,&#34;ServerID&#34;:&#34;953c393d-e6a7-4c50-a4a1-5c26b3e8cc4c&#34;},&#34;ID&#34;:&#34;kapacitor/cpu/serverA&#34;,&#34;Fields&#34;:{&#34;count&#34;:10},&#34;Level&#34;:&#34;CRITICAL&#34;,&#34;Time&#34;:&#34;1971-01-01T00:00:10Z&#34;,&#34;Duration&#34;:0,&#34;Message&#34;:&#34;CRITICAL alert for kapacitor/cpu/serverA&#34;}\n"
		  }
		 },
		 (pagerdutytest.Request) {
		  URL: (string) (len=1) "/",
		  PostData: (pagerdutytest.PostData) {
		   ServiceKey: (string) (len=17) "test_override_key",
		   EventType: (string) (len=7) "trigger",
		   Description: (string) (len=40) "CRITICAL alert for kapacitor/cpu/serverA",
		   Client: (string) (len=9) "kapacitor",
		   ClientURL: (string) (len=30) "http://[::]:39856/kapacitor/v1",
		   Details: (string) (len=615) "{&#34;Name&#34;:&#34;cpu&#34;,&#34;TaskName&#34;:&#34;TestStream_Alert&#34;,&#34;Group&#34;:&#34;host=serverA&#34;,&#34;Tags&#34;:{&#34;host&#34;:&#34;serverA&#34;},&#34;ServerInfo&#34;:{&#34;Hostname&#34;:&#34;localhost&#34;,&#34;ClusterID&#34;:&#34;3d0c012f-06cc-4415-a388-9221d12bf14c&#34;,&#34;ServerID&#34;:&#34;953c393d-e6a7-4c50-a4a1-5c26b3e8cc4c&#34;},&#34;ID&#34;:&#34;kapacitor/cpu/serverA&#34;,&#34;Fields&#34;:{&#34;count&#34;:10},&#34;Level&#34;:&#34;CRITICAL&#34;,&#34;Time&#34;:&#34;1971-01-01T00:00:10Z&#34;,&#34;Duration&#34;:0,&#34;Message&#34;:&#34;CRITICAL alert for kapacitor/cpu/serverA&#34;}\n"
		  }
		 }
		}
		
		exp
		([]interface {}) (len=2 cap=2) {
		 (pagerdutytest.Request) {
		  URL: (string) (len=1) "/",
		  PostData: (pagerdutytest.PostData) {
		   ServiceKey: (string) (len=11) "service_key",
		   EventType: (string) (len=7) "trigger",
		   Description: (string) (len=40) "CRITICAL alert for kapacitor/cpu/serverA",
		   Client: (string) (len=9) "kapacitor",
		   ClientURL: (string) (len=30) "http://[::]:39856/kapacitor/v1",
		   Details: (string) (len=594) "{&#34;Name&#34;:&#34;cpu&#34;,&#34;TaskName&#34;:&#34;TestStream_Alert&#34;,&#34;Group&#34;:&#34;host=serverA&#34;,&#34;Tags&#34;:{&#34;host&#34;:&#34;serverA&#34;},&#34;ServerInfo&#34;:{&#34;Hostname&#34;:&#34;localhost&#34;,&#34;ClusterID&#34;:&#34;3d0c012f-06cc-4415-a388-9221d12bf14c&#34;,&#34;ServerID&#34;:&#34;953c393d-e6a7-4c50-a4a1-5c26b3e8cc4c&#34;},&#34;ID&#34;:&#34;kapacitor/cpu/serverA&#34;,&#34;Fields&#34;:{&#34;count&#34;:10},&#34;Level&#34;:&#34;CRITICAL&#34;,&#34;Time&#34;:&#34;1971-01-01T00:00:10Z&#34;,&#34;Message&#34;:&#34;CRITICAL alert for kapacitor/cpu/serverA&#34;}\n"
		  }
		 },
		 (pagerdutytest.Request) {
		  URL: (string) (len=1) "/",
		  PostData: (pagerdutytest.PostData) {
		   ServiceKey: (string) (len=17) "test_override_key",
		   EventType: (string) (len=7) "trigger",
		   Description: (string) (len=40) "CRITICAL alert for kapacitor/cpu/serverA",
		   Client: (string) (len=9) "kapacitor",
		   ClientURL: (string) (len=30) "http://[::]:39856/kapacitor/v1",
		   Details: (string) (len=594) "{&#34;Name&#34;:&#34;cpu&#34;,&#34;TaskName&#34;:&#34;TestStream_Alert&#34;,&#34;Group&#34;:&#34;host=serverA&#34;,&#34;Tags&#34;:{&#34;host&#34;:&#34;serverA&#34;},&#34;ServerInfo&#34;:{&#34;Hostname&#34;:&#34;localhost&#34;,&#34;ClusterID&#34;:&#34;3d0c012f-06cc-4415-a388-9221d12bf14c&#34;,&#34;ServerID&#34;:&#34;953c393d-e6a7-4c50-a4a1-5c26b3e8cc4c&#34;},&#34;ID&#34;:&#34;kapacitor/cpu/serverA&#34;,&#34;Fields&#34;:{&#34;count&#34;:10},&#34;Level&#34;:&#34;CRITICAL&#34;,&#34;Time&#34;:&#34;1971-01-01T00:00:10Z&#34;,&#34;Message&#34;:&#34;CRITICAL alert for kapacitor/cpu/serverA&#34;}\n"
		  }
		 }
		}
		
```
From the looks of it I think the `exp` is missing a `Duration` in the details field.

**Comment by thuck** [comment]
cool, I'll take a look later on this.

**Comment by thuck** [comment]
@desa Looks like CircleCI had some issue; but running on my machine I don't have any error:
```
thuck@debian:~/go/src/github.com/influxdata/kapacitor$ python build.py 
[INFO] print_banner: 

'##:::'##::::'###::::'########:::::'###:::::'######::'####:'########::'#######::'########::
 ##::'##::::'## ##::: ##.... ##:::'## ##:::'##... ##:. ##::... ##..::'##.... ##: ##.... ##:
 ##:'##::::'##:. ##:: ##:::: ##::'##:. ##:: ##:::..::: ##::::: ##:::: ##:::: ##: ##:::: ##:
 #####::::'##:::. ##: ########::'##:::. ##: ##:::::::: ##::::: ##:::: ##:::: ##: ########::
 ##. ##::: #########: ##.....::: #########: ##:::::::: ##::::: ##:::: ##:::: ##: ##.. ##:::
 ##:. ##:: ##.... ##: ##:::::::: ##.... ##: ##::: ##:: ##::::: ##:::: ##:::: ##: ##::. ##::
 ##::. ##: ##:::: ##: ##:::::::: ##:::: ##:. ######::'####:::: ##::::. #######:: ##:::. ##:
..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::..:::::..::
 Build Script

[INFO] check_environ: Checking environment...
[INFO] check_prereqs: Checking for dependencies...
[INFO] build: Starting build for linux/amd64...
[INFO] build: Using Go version: 1.9.1
[INFO] build: Using git branch: fr_duration_on_message
[INFO] build: Using git commit: f7211eb355b5f750924f727c590e597eaf556842
[INFO] build: Sending build output to: /home/thuck/go/src/github.com/influxdata/kapacitor/build
[INFO] build: Using version '1.3.3' for build.
[INFO] build: Building target: kapacitord
[INFO] build: Time taken: 20.478383s
[INFO] build: Building target: kapacitor
[INFO] build: Time taken: 0.801441s
[INFO] build: Building target: tickfmt
[INFO] build: Time taken: 0.218119s
thuck@debian:~/go/src/github.com/influxdata/kapacitor$ 
thuck@debian:~/go/src/github.com/influxdata/kapacitor$ python build.py --test --parallel 20
[INFO] print_banner: 

'##:::'##::::'###::::'########:::::'###:::::'######::'####:'########::'#######::'########::
 ##::'##::::'## ##::: ##.... ##:::'## ##:::'##... ##:. ##::... ##..::'##.... ##: ##.... ##:
 ##:'##::::'##:. ##:: ##:::: ##::'##:. ##:: ##:::..::: ##::::: ##:::: ##:::: ##: ##:::: ##:
 #####::::'##:::. ##: ########::'##:::. ##: ##:::::::: ##::::: ##:::: ##:::: ##: ########::
 ##. ##::: #########: ##.....::: #########: ##:::::::: ##::::: ##:::: ##:::: ##: ##.. ##:::
 ##:. ##:: ##.... ##: ##:::::::: ##.... ##: ##::: ##:: ##::::: ##:::: ##:::: ##: ##::. ##::
 ##::. ##: ##:::: ##: ##:::::::: ##:::: ##:. ######::'####:::: ##::::. #######:: ##:::. ##:
..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::..:::::..::
 Build Script

[INFO] check_environ: Checking environment...
[INFO] check_prereqs: Checking for dependencies...
[INFO] run_tests: Starting tests...
[INFO] run_tests: Using parallel: 20
[INFO] run_tests: Running tests...
[INFO] build: Starting build for linux/amd64...
[INFO] build: Using Go version: 1.9.1
[INFO] build: Using git branch: fr_duration_on_message
[INFO] build: Using git commit: f7211eb355b5f750924f727c590e597eaf556842
[INFO] build: Sending build output to: /home/thuck/go/src/github.com/influxdata/kapacitor/build
[INFO] build: Using version '1.3.3' for build.
[INFO] build: Building target: kapacitord
[INFO] build: Time taken: 20.715519s
[INFO] build: Building target: kapacitor
[INFO] build: Time taken: 0.80416s
[INFO] build: Building target: tickfmt
[INFO] build: Time taken: 0.212139s

```

**Comment by thuck** [comment]
@nathanielc No problem at all; I'll update this later today.

**Comment by thuck** [comment]
@nathanielc anything else that you think it would be important before this code can be merged?

**Pull request merged**
